apiVersion: v1
kind: ConfigMap
metadata:
  name: webflow-ssl-proxy
  labels:
    app.kubernetes.io/managed-by: Helm
    meta.helm.sh/release-name: webflow-ssl-proxy
data:
  kubernetes.conf: |
    Options FollowSymLinks ExecCGI
    ProxyPreserveHost off

    <VirtualHost *:80>
        ServerName webflow-ssl-proxy-80
        ServerAlias *

        # Add X-Forwarded-Proto header
        RequestHeader set X-Forwarded-Proto "https"

        # Proxy requests to backend server, but "fake" a different hostname (mindsdb.com) needed because of how webflow works
        ProxyRemote "*" "http://proxy.webflow.com"
        ProxyPass / "http://mindsdb.com/"
        ProxyPassReverse / "http://mindsdb.com/"
    </VirtualHost>
  # IMPLEMENTATION NOTE: Uncomment below to debug raw any requests sent to proxies and such
  # zz-debug.conf: |
  #   LoadModule dumpio_module modules/mod_dumpio.so
  #   LogLevel dumpio:trace7
  #   DumpIOInput On
  #   DumpIOOutput On
