# Default values for deployment, this is necessary because we're using a unified helm subchart
deployment:
  # This is the name of the deployment, this is used in a _lot_ of places in the helm charts so lets just specify it
  name: webflow-ssl-proxy

  replicaCount: 1

  # This runs on Linux only
  nodeSelector:
    kubernetes.io/os: linux

  # Where our ECR registry is and what tag to use, along with the command/arguments if desired.  See helm chart
  image:
    repository: andrewfarley/docker-kubernetes-apache-proxy
    tag: latest

  # livenessProbes are used to determine when to restart a container
  # Only specify the values you need to override from the defaults
  livenessProbe:
    enabled: true
    initialDelaySeconds: 30
    path: /

  # readinessProbes are used to determine when a container is ready to start accepting traffic
  # Only specify the values you need to override from the defaults
  readinessProbe:
    enabled: true
    initialDelaySeconds: 1
    path: /

  # deployment container resource requests/limits
  # this is set VERY low by default, to be aggressive above resource limiting, please override this if necessary
  # Note: Limits are HARD Limits
  #       Requests are "soft" limits and are what affects HPA (autoscaling) aggressiveness if HPA is enabled
  resources:
    limits:
      cpu: 1
      memory: 100Mi
    requests:
      cpu: 50m
      memory: 100Mi

  # Enable autoscaling (prod only)
  autoscaling:
    enabled: false
    minReplicas: 3

  ingress:
    enabled: true
    ingressClassName: "infrastructure"
    annotations:
      # support large file uploads
      nginx.ingress.kubernetes.io/proxy-body-size: "1000m"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    hosts:
      - host: REPLACE_HOSTNAME_IN_ENV_VALUES
        paths:
          - /(/+)?(.*)

  volumes:
    - name: config-volume
      configMap:
        name: webflow-ssl-proxy

  volumeMounts:
    - name: config-volume
      mountPath: /usr/local/apache2/conf/kubernetes
