---
# Default values for prod
deployment:

  # Only on prod we want high-availability & scalability
  autoscaling:
    enabled: true

  # This is setup to route from the nginx-ingress controller which is the actual public interface
  ingress:
    hosts:
      - host: 'docs.mdb.ai'
        paths:
          - /
